### ISSUE TITLE
Add CSS/JS animations/transitions to existing frontend

### ISSUE THREAD

**Issue by choyiny** [choyiny/answer-me#2]
Replace the barebones frontend with a fancier one.

**Comment by AdrianJVillalobos** [comment]
Hello I'm interested in this issue, can you give me more details? I would like to take this at @NovaHelm

**Comment by bharati-21** [comment]
Has this issue  been taken by someone? I'm interested!

**Comment by choyiny** [comment]
If you could clone the project, try and set it up, you can see the frontend UI is actually pretty bad. Using your creativity, come up with a better UI that is mobile-first (game is played on the phone).

**Comment by choyiny** [comment]
Both of you can work on it, I will try to accommodate both of you @bharati-21 @AdrianJVillalobos

**Comment by AdrianJVillalobos** [comment]
@choyiny only one of us can be assigned to this issue

**Comment by choyiny** [comment]
There are many components you can beautify:
1. Beautify the game screen
2. Beautify the tv screen
3. Beautify the admin screen

**Comment by choyiny** [comment]
I have thought about it more. It makes sense to descope it, and make it so that existing frontend could have css/js animations added to it to make it more engaging.

**Comment by AdrianJVillalobos** [comment]
Hello @choyiny both of us (bharati-21 and I) can't be assigned in this same issue, I'm ready to start working on this right now.

**Comment by bharati-21** [comment]
Sure @AdrianJVillalobos ! I might take some time if I work on this. Please go ahead :) :D

**Comment by AdrianJVillalobos** [comment]
> Sure @AdrianJVillalobos ! I might take some time if I work on this. Please go ahead :) :D

@bharati-21 thank you!

**Comment by AdrianJVillalobos** [comment]
Hello! @choyiny I'm ready to put my hands on this, assign me and I'll start coding

**Comment by choyiny** [comment]
@AdrianJVillalobos any updates on this?

**Comment by AdrianJVillalobos** [comment]
Pardon me, I'm working on your project but at a slow pace, usually I'm not this kind of busy. 
I'll work on this project for this week.
